CentralCoastMusic/Controllers/ArtistController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using CentralCoastMusic.Models;
using CentralCoastMusic.Services;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

namespace CentralCoastMusic.Controllers
{
    public class ArtistController : Controller
    {
        private readonly ILogger<ArtistController> _logger;
        private readonly ArtistService _artistService;
        private readonly AuthService _authService;
        private readonly TagService _tagService;
        private readonly StreamService _streamService;
        private readonly ImageService _imageService;


        public ArtistController(ILogger<ArtistController> logger,
                                ArtistService artistService,
                                AuthService authService,
                                TagService tagService,
                                StreamService streamService,
                                ImageService imageService)
        {
            _logger = logger;
            _artistService = artistService;
            _authService = authService;
            _tagService = tagService;
            _streamService = streamService;
            _imageService = imageService;
        }
        /// <summary>
        /// Gets the login page for artists or returns their details if they're logged in
        /// </summary>
        /// <returns></returns>
        public ActionResult Index()
        {
            ViewData["jsSettings"] = AppSettings.AppSetting["jsSettings"];
            var dict = GetCookies();
            //Check to see if logged in
            if (dict["uid"] != null && dict["token"] != null)
            {
                return RedirectToAction("Details");
            }
            else
            {                
                return View();
            }            
        }

        /// <summary>
        /// Gets the artist details of the person logged in
        /// </summary>
        /// <returns></returns>
        public async Task<IActionResult> Details()
        {
            var id = GetCookies();
            var artist = await _artistService.GetArtist(id["uid"]);
            //ViewData["Tags"] = await _tagService.GetTags(id["uid"]);
            //ViewData["Streams"] = await _linkService.GetStreams(id["uid"]);
            if (artist!=null)
            {
                return View(artist);
            }
            else
            {
                return RedirectToAction("Create");
            }
        }

        /// <summary>
        /// View to create an artist's profile
        /// </summary>
        /// <returns></returns>
        public IActionResult Create()
        {
            var auth = GetCookies();
            return View();
        }

        /// <summary>
        /// Creates the artist from the provided form
        /// Tags, Streams, and Images are created separately
        /// </summary>
        /// <param name="artist"></param>
        /// <returns></returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(Artist artist)
        {
            var auth = GetCookies();
            artist.Id = auth["uid"];
            try
            {
                var artistRequest = new ArtistRequest()
                {
                    Auth = auth,
                    Artist = artist
                };
                await _artistService.AddArtist(artistRequest);
                return RedirectToAction("Details");
            }
            catch
            {
                //TODO send in error back to view
                return View();
            }
        }

        /// <summary>
        /// Edit the artist page, returns to detail page if not authorized
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public async Task<ActionResult> Edit(string id)
        {
            var auth = GetCookies();

            if (auth["uid"]==id)
            {
                var artist = await _artistService.GetArtist(id);
                //ViewData["Tags"] = await _tagService.GetTags(id);
                //ViewData["Streams"] = await _streamService.GetStreams(id);
                return View(artist);
            }
            else
            {
                return RedirectToAction("Detail", "Music",id);
            }

        }

        /// <summary>
        /// Performs the artist edit
        /// </summary>
        /// <param name="artist"></param>
        /// <returns></returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(Artist artist)
        {
            var auth = GetCookies();
            string imageUrl = null;
            try
            {
                //We're not attaching the profile image url until this point. If you don't save, it gets orphaned
                var imageId = await _imageService.GetProfileImage(artist.Id);

                if (imageId!="")
                {
                    imageUrl = _imageService.GetImage("ProfileImage/" + imageId);
                }

                artist.ImageUrl = imageUrl;

                var artistRequest = new ArtistRequest()
                {
                    Auth = auth,
                    Artist = artist
                };
                await _artistService.EditArtist(artistRequest);
                
                return RedirectToAction("Details");
            }
            catch
            {
                //TODO errors
                return View();
            }
        }    
        /// <summary>
        /// Privacy Policy
        /// </summary>
        /// <returns></returns>
        public IActionResult Privacy()
        {
            return View();
        }
        /// <summary>
        /// Help page
        /// </summary>
        /// <returns></returns>
        public IActionResult Help()
        {
            return View();
        }
        /// <summary>
        /// Removes the auth cookies
        /// </summary>
        /// <returns></returns>
        public IActionResult Logout()
        {
            Remove("uid");
            Remove("token");
            return RedirectToAction("Index");
        }

        #region Cookie Management

        public async Task<bool> SetAuth(string auth, string uid)
        {
            var dict = GetCookies();

            var rq = HttpContext.Request.Headers;

            var a = rq["uid"];
            var b = rq["token"];
            var x = HttpContext.User;

            if (a.ToString() == null || b.ToString() == null)
            {
                a = dict["uid"];
                b = dict["token"];
            }

            if (a == await _authService.Google(b))
            {
                if (dict["uid"] == null && dict["token"] == null)
                {
                    Set("token", b, 720);
                    Set("uid", a, 720);
                }
                    return true;
            }
            else
            {
                return false;
            }
        }

        public Dictionary<string, string> GetCookies()
        {
            return new Dictionary<string, string>()
            {
                {"uid", Get("uid")},
                {"token", Get("token") }
            };
        }

        /// <summary>  
        /// Get the cookie  
        /// </summary>  
        /// <param name="key">Key </param>  
        /// <returns>string value</returns>  
        public string Get(string key)
        {
            return Request.Cookies[key];
        }
        /// <summary>  
        /// set the cookie  
        /// </summary>  
        /// <param name="key">key (unique indentifier)</param>  
        /// <param name="value">value to store in cookie object</param>  
        /// <param name="expireTime">expiration time</param>  
        public void Set(string key, string value, int? expireTime)
        {
            CookieOptions option = new CookieOptions();
            if (expireTime.HasValue)
                option.Expires = DateTime.Now.AddMinutes(expireTime.Value);
            else
                option.Expires = DateTime.Now.AddMilliseconds(100000);
            Response.Cookies.Append(key, value, option);
        }
        /// <summary>  
        /// Delete the key  
        /// </summary>  
        /// <param name="key">Key</param>  
        public void Remove(string key)
        {
            Response.Cookies.Delete(key);
        }
        #endregion
    }
}

CentralCoastMusic/Controllers/MusicController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using CentralCoastMusic.Models;
using CentralCoastMusic.Services;

namespace CentralCoastMusic.Controllers
{
    public class MusicController : Controller
    {
        private readonly ILogger<MusicController> _logger;
        private readonly ArtistService _artistService;
        private readonly StreamService _streamService;

        public MusicController(ILogger<MusicController> logger,
                                ArtistService artistService,
                                StreamService streamService)
        {
            _logger = logger;
            _artistService = artistService;
            _streamService = streamService;
        }
        /// <summary>
        /// First load grabs all artists
        /// </summary>
        /// <returns></returns>
        public IActionResult Index()
        {
            return View();
        }
        /// <summary>
        /// Gets all the artists
        /// </summary>
        /// <returns></returns>
        public async Task<IActionResult> GetArtists(int limit = 0, int offset=0)
        {
            //TODO Paginate this... lazy load?
            var artists = await _artistService.GetArtists();

            artists = await _streamService.AddUpcomingStreamToArtists(artists);
            
            return PartialView(artists);
        }
        /// <summary>
        /// Searches artist names on a string
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public async Task<IActionResult> ArtistSearch(string id)
        {
            var artists = await _artistService.SearchArtists(id);
            artists = await _streamService.AddUpcomingStreamToArtists(artists);
            return PartialView("GetArtists", artists);
        }
        /// <summary>
        /// searches artists by tag
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public async Task<IActionResult> TagSearch(string id)
        {
            var artists = await _artistService.TagSearch(id);
            artists = await _streamService.AddUpcomingStreamToArtists(artists);
            return PartialView("GetArtists", artists);
        }

        /// <summary>
        /// Get details of specific artist
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public async Task<IActionResult> Details(string id)
        {
            var artist = await _artistService.GetArtist(id);
            if (artist != null)
            {
                //adds streams to artist
                var artists = await _streamService.AddUpcomingStreamToArtists(new List<Artist>() { artist});

                return PartialView(artists.FirstOrDefault());
            }
            else
            {
                return RedirectToAction("Index");
            }
        }
        /// <summary>
        /// About section
        /// </summary>
        /// <returns></returns>
        public IActionResult About()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

CentralCoastMusic/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CentralCoastMusic</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">CentralCoastMusic</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Music" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Artist" asp-action="Index">Artist Management</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Artist" asp-action="Privacy">Privacy</a>
                        </li>
                        @if (Context.Request.Cookies["uid"] != null)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Artist" asp-action="Logout">Log Out</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            <!-- Insert these scripts at the bottom of the HTML, but before you use any Firebase services -->
            <!-- Firebase App (the core Firebase SDK) is always required and must be listed first -->
            <script src="https://www.gstatic.com/firebasejs/7.12.0/firebase-app.js"></script>

            <!-- If you enabled Analytics in your project, add the Firebase SDK for Analytics -->
            <script src="https://www.gstatic.com/firebasejs/7.12.0/firebase-analytics.js"></script>

            <!-- Add Firebase products that you want to use -->
            <script src="https://www.gstatic.com/firebasejs/7.12.0/firebase-auth.js"></script>
            <script src="https://www.gstatic.com/firebasejs/7.12.0/firebase-firestore.js"></script>
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - CentralCoastMusic - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>