CentralCoastMusic/Models/Artist.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CentralCoastMusic.Models
{
    public class Artist
    {
        public string Id { get; set; }
        public string Name { get; set; }
        public string ImageUrl { get; set; }
        public string Youtube { get; set; }
        public string Instagram { get; set; }
        public string Facebook { get; set; }
        public string Patreon { get; set; }
        public string Twitter { get; set; }
        public string Donation { get; set; }
        public string Livestream { get; set; }
        public DateTime? NextLivestream { get; set; }
        public string LiveStreamId { get; set; }
        public bool Verified { get; set; }
        public string CustomUrl { get; set; }

        //public List<string> Genres { get; set; }

    }
}

CentralCoastMusic/Controllers/ArtistController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using CentralCoastMusic.Models;
using CentralCoastMusic.Services;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

namespace CentralCoastMusic.Controllers
{
    public class ArtistController : Controller
    {
        private readonly ILogger<ArtistController> _logger;
        private readonly ArtistService _artistService;
        private readonly AuthService _authService;
        private readonly TagService _tagService;
        private readonly StreamService _streamService;
        private readonly ImageService _imageService;


        public ArtistController(ILogger<ArtistController> logger,
                                ArtistService artistService,
                                AuthService authService,
                                TagService tagService,
                                StreamService streamService,
                                ImageService imageService)
        {
            _logger = logger;
            _artistService = artistService;
            _authService = authService;
            _tagService = tagService;
            _streamService = streamService;
            _imageService = imageService;
        }
        /// <summary>
        /// Gets the login page for artists or returns their details if they're logged in
        /// </summary>
        /// <returns></returns>
        public ActionResult Index()
        {
            ViewData["jsSettings"] = AppSettings.AppSetting["jsSettings"];
            var dict = GetCookies();
            //Check to see if logged in
            if (dict["uid"] != null && dict["token"] != null)
            {
                return RedirectToAction("Details");
            }
            else
            {                
                return View();
            }            
        }

        /// <summary>
        /// Gets the artist details of the person logged in
        /// </summary>
        /// <returns></returns>
        public async Task<IActionResult> Details()
        {
            var id = GetCookies();
            var artist = await _artistService.GetArtist(id["uid"]);
            //ViewData["Tags"] = await _tagService.GetTags(id["uid"]);
            //ViewData["Streams"] = await _linkService.GetStreams(id["uid"]);
            if (artist!=null)
            {
                return View(artist);
            }
            else
            {
                return RedirectToAction("Create");
            }
        }

        /// <summary>
        /// View to create an artist's profile
        /// </summary>
        /// <returns></returns>
        public IActionResult Create()
        {
            var auth = GetCookies();
            return View();
        }

        /// <summary>
        /// Creates the artist from the provided form
        /// Tags, Streams, and Images are created separately
        /// </summary>
        /// <param name="artist"></param>
        /// <returns></returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(Artist artist)
        {
            var auth = GetCookies();
            artist.Id = auth["uid"];
            try
            {
                var artistRequest = new ArtistRequest()
                {
                    Auth = auth,
                    Artist = artist
                };
                await _artistService.AddArtist(artistRequest);
                return RedirectToAction("Details");
            }
            catch
            {
                //TODO send in error back to view
                return View();
            }
        }

        /// <summary>
        /// Edit the artist page, returns to detail page if not authorized
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public async Task<ActionResult> Edit(string id)
        {
            var auth = GetCookies();

            if (auth["uid"]==id)
            {
                var artist = await _artistService.GetArtist(id);
                //ViewData["Tags"] = await _tagService.GetTags(id);
                //ViewData["Streams"] = await _streamService.GetStreams(id);
                return View(artist);
            }
            else
            {
                return RedirectToAction("Detail", "Music",id);
            }

        }

        /// <summary>
        /// Performs the artist edit
        /// </summary>
        /// <param name="artist"></param>
        /// <returns></returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(Artist artist)
        {
            var auth = GetCookies();
            string imageUrl = null;
            try
            {
                //We're not attaching the profile image url until this point. If you don't save, it gets orphaned
                var imageId = await _imageService.GetProfileImage(artist.Id);

                if (imageId!="")
                {
                    imageUrl = _imageService.GetImage("ProfileImage/" + imageId);
                }

                artist.ImageUrl = imageUrl;

                var artistRequest = new ArtistRequest()
                {
                    Auth = auth,
                    Artist = artist
                };
                await _artistService.EditArtist(artistRequest);
                
                return RedirectToAction("Details");
            }
            catch
            {
                //TODO errors
                return View();
            }
        }    
        /// <summary>
        /// Privacy Policy
        /// </summary>
        /// <returns></returns>
        public IActionResult Privacy()
        {
            return View();
        }
        /// <summary>
        /// Help page
        /// </summary>
        /// <returns></returns>
        public IActionResult Help()
        {
            return View();
        }
        /// <summary>
        /// Removes the auth cookies
        /// </summary>
        /// <returns></returns>
        public IActionResult Logout()
        {
            Remove("uid");
            Remove("token");
            return RedirectToAction("Index");
        }

        #region Cookie Management

        public async Task<bool> SetAuth(string auth, string uid)
        {
            var dict = GetCookies();

            var rq = HttpContext.Request.Headers;

            var a = rq["uid"];
            var b = rq["token"];
            var x = HttpContext.User;

            if (a.ToString() == null || b.ToString() == null)
            {
                a = dict["uid"];
                b = dict["token"];
            }

            if (a == await _authService.Google(b))
            {
                if (dict["uid"] == null && dict["token"] == null)
                {
                    Set("token", b, 720);
                    Set("uid", a, 720);
                }
                    return true;
            }
            else
            {
                return false;
            }
        }

        public Dictionary<string, string> GetCookies()
        {
            return new Dictionary<string, string>()
            {
                {"uid", Get("uid")},
                {"token", Get("token") }
            };
        }

        /// <summary>  
        /// Get the cookie  
        /// </summary>  
        /// <param name="key">Key </param>  
        /// <returns>string value</returns>  
        public string Get(string key)
        {
            return Request.Cookies[key];
        }
        /// <summary>  
        /// set the cookie  
        /// </summary>  
        /// <param name="key">key (unique indentifier)</param>  
        /// <param name="value">value to store in cookie object</param>  
        /// <param name="expireTime">expiration time</param>  
        public void Set(string key, string value, int? expireTime)
        {
            CookieOptions option = new CookieOptions();
            if (expireTime.HasValue)
                option.Expires = DateTime.Now.AddMinutes(expireTime.Value);
            else
                option.Expires = DateTime.Now.AddMilliseconds(100000);
            Response.Cookies.Append(key, value, option);
        }
        /// <summary>  
        /// Delete the key  
        /// </summary>  
        /// <param name="key">Key</param>  
        public void Remove(string key)
        {
            Response.Cookies.Delete(key);
        }
        #endregion
    }
}

CentralCoastMusic/Controllers/ImageController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using CentralCoastMusic.Models;
using CentralCoastMusic.Services;
using Google.Apis.Auth.OAuth2;
using Google.Cloud.Storage.V1;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace CentralCoastMusic.Controllers
{
    public class ImageController : Controller
    {
        private readonly ImageService _imageService;
        private readonly ArtistService _artistService;
        private readonly StreamService _streamService;
        public ImageController(ImageService imageService, ArtistService artistService,StreamService streamService)
        {
            _imageService = imageService;
            _artistService = artistService;
            _streamService = streamService;
        }

        /// <summary>
        /// Uploads the actual image file
        /// </summary>
        /// <param name="type"></param>
        /// <returns></returns>
        [HttpPost]
        public async Task<ActionResult> UploadImage(string type)
        {
            HttpContext.Request.Cookies.TryGetValue("uid", out string user);
            HttpContext.Request.Cookies.TryGetValue("token", out string token);
            var auth = new Dictionary<string, string>()
            {
                {"uid", user },
                {"token",token }
            };

            var file = Request.Form.Files.FirstOrDefault();

            //Give file a GUID as a name
            var id = Guid.NewGuid().ToString();
            //upload that file                                   
            _imageService.UploadFile(file,id);
            //get that profileimage linked to user
            await _imageService.AddProfileImage(auth, id);

            return Ok();
        }
        /// <summary>
        /// Returns the image url for the image you're requesting
        /// </summary>
        /// <param name="id"></param>
        /// <param name="type"></param>
        /// <returns></returns>
        [HttpGet]
        public async Task<string> GetImage(string id, string type)
        {
            var imageId = "";
            switch(type)
            {
                case "ProfileImage":
                    imageId = await _imageService.GetProfileImage(id);                    
                    break;

            }
            //need to figure out stream images

            //Get file guid from profile id
            //Return that image
            return _imageService.GetImage(type + "/" + imageId);
        }

        /// <summary>
        /// Removes the image for the logged in user
        /// </summary>
        /// <param name="type"></param>
        /// <returns></returns>
        [HttpDelete]
        public async Task<ActionResult> RemoveImage(string type)
        {
            //Get file guid from profile id
            //Remove that image
            //Remove that id                
            HttpContext.Request.Cookies.TryGetValue("uid", out string user);
            HttpContext.Request.Cookies.TryGetValue("token", out string token);
            var auth = new Dictionary<string, string>()
            {
                {"uid", user },
                {"token",token }
            };

            var imageId = await _imageService.GetProfileImage(user);

            _imageService.RemoveImage(type+"/"+imageId);
            await _imageService.RemoveProfileImage(auth, user);

            return Ok();

        }
    }
}

CentralCoastMusic/Views/Artist/Create.cshtml
@model CentralCoastMusic.Models.Artist

@{
    ViewData["Title"] = "Create";
}

<link rel="stylesheet" href="~/css/croppie.css" />

<h1>Create</h1>

<h4>Artist</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Youtube" class="control-label"></label>
                <input asp-for="Youtube" class="form-control" />
                <span asp-validation-for="Youtube" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Instagram" class="control-label"></label>
                <input asp-for="Instagram" class="form-control" />
                <span asp-validation-for="Instagram" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Facebook" class="control-label"></label>
                <input asp-for="Facebook" class="form-control" />
                <span asp-validation-for="Facebook" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Patreon" class="control-label"></label>
                <input asp-for="Patreon" class="form-control" />
                <span asp-validation-for="Patreon" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Twitter" class="control-label"></label>
                <input asp-for="Twitter" class="form-control" />
                <span asp-validation-for="Twitter" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Donation" class="control-label"></label>
                <input asp-for="Donation" class="form-control" />
                <span asp-validation-for="Donation" class="text-danger"></span>
            </div>
            <div class="form-group">
                <div id="imagePreview">
                    <input type="file" accept="image/*" onchange="loadFile(event)">
                    <img id="output" hidden />
                </div>
                <div id="imageUpload">Will have image uploads here</div>
                <div class="btn" onclick="uploadImage()">Upload</div>
            </div>
            <div class="form-group" id="tagContainer" name="tagContainer">
                <input class="form-control" id="tags" placeholder="Enter three genres that describe your music" /><span onclick="addTag()">+</span>
                <div id="tagList" name="tagList"></div>
            </div>
            <div class="form-group" id="livestreamContainer" name="livestreamContainer">
                <div id="livestreamInput">
                    <input class="form-control" id="streamDesc" placeholder="Decribe your stream" maxlength="30" /><input class="form-control" id="streamDate" type="datetime-local" /><input class="form-control" id="streamLink" placeholder="Link to your livestream" /><span onclick="addLivestream()">+</span>
                </div>
                <div id="livestreamList" name="livestreamList"></div>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    <script src="~/js/croppie.js"></script>
    <script src="~/js/dropzone.min.js"></script>


    <script>
        var uploadCrop = $('#imageUpload').croppie({
            viewport: {
                width: 200,
                height: 200,
                type: 'square'
            },
            boundary: {
                width: 300,
                height: 300
            }
        });        

        var loadFile = function (event) {
            var output = document.getElementById('output');
            output.src = URL.createObjectURL(event.target.files[0]);
            output.onload = function () {
                 uploadCrop.croppie('bind', {
                     url: output.src
                });
                URL.revokeObjectURL(output.src) // free memory
            }
        };

        function uploadImage() {
            uploadCrop.croppie('result','blob').then(function(blob) {
                var formData = new FormData();
                formData.append('filename', 'profile.png');
                formData.append('blob', blob);
                var MyAppUrlSettings = {
                    MyUsefulUrl: '@Url.Action("UploadImage","Image")'
                }

                var request = new XMLHttpRequest();
                request.open('POST', MyAppUrlSettings.MyUsefulUrl);
                request.send(formData);
            });
        }


        var tagCounter = 0
        function addTag() {
            if ($('#tagList').children('input').length < 3) {
                var tagObj = new Object();
                tagObj.Name = $('#tags').val();
                $.ajax({
                    type: "POST",
                    url: "../../Link/AddTag",
                    contentType: 'application/json',
                    data: JSON.stringify(tagObj),
                    success: function (data) {
                        var dataStr = "'" + data + "'";
                        $('#tagList').append('<input id="' + data + '" value="' + $('#tags').val() + '" onclick="tagRemove(' + dataStr + ')"/>'); $('#tags').val('');
                    }
                });
            } else {
                $('#tags').val('');
                $('#tags').attr('placeholder', 'Please remove a tag to add a new one');
            }
        }

        function addLivestream() {
            var streamObj = new Object();
            streamObj.Name = $('#streamDesc').val();
            streamObj.Description = $('#streamLink').val();
            streamObj.StartTime = $('#streamDate').val();

            $.ajax({
                type: "POST",
                url: "../../Link/AddStream",
                contentType: 'application/json',
                data: JSON.stringify(streamObj),
                success: function (data) {
                    var dataStr = "'" + data + "'";
                    $('#livestreamList').append('<div id="' + data + '" onclick="streamRemove(' + dataStr + ')"><span>-</span>' + $('#streamDesc').val() + ' on ' + $('#streamDate').val() + ' viewable at ' + $('#streamLink').val() + '</div>');
                    $('#livestreamInput').find('input').val('');
                }
            });
        }

        function tagRemove(id) {
            $.ajax({
                type: "POST",
                url: "../../Link/RemoveTag/" + id,
                contentType: 'application/json',
                success: function (data) {
                    $('#' + id).remove();
                    $('#tags').attr('placeholder', 'Enter three genres that describe your music');

                }
            });
        }

        function streamRemove(id) {
            $.ajax({
                type: "POST",
                url: "../../Link/RemoveStream/" + id,
                contentType: 'application/json',
                success: function (data) {
                    $('#' + id).remove();
                }
            });
        }
    </script>

}

CentralCoastMusic/Views/Artist/Dashboard.cshtml
@{
    ViewData["Title"] = "Dashboard";
}

<h1>Dashboard</h1>

CentralCoastMusic/Views/Artist/Edit.cshtml
@model CentralCoastMusic.Models.Artist

@{
    ViewData["Title"] = "Edit";
}


<link rel="stylesheet" href="~/css/croppie.css" />

<h1>Edit</h1>

<h4>Artist</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form id="artistEditor" asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Youtube" class="control-label"></label>
                <input asp-for="Youtube" class="form-control" />
                <span asp-validation-for="Youtube" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Instagram" class="control-label"></label>
                <input asp-for="Instagram" class="form-control" />
                <span asp-validation-for="Instagram" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Facebook" class="control-label"></label>
                <input asp-for="Facebook" class="form-control" />
                <span asp-validation-for="Facebook" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Patreon" class="control-label"></label>
                <input asp-for="Patreon" class="form-control" />
                <span asp-validation-for="Patreon" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Twitter" class="control-label"></label>
                <input asp-for="Twitter" class="form-control" />
                <span asp-validation-for="Twitter" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Donation" class="control-label"></label>
                <input asp-for="Donation" class="form-control" />
                <span asp-validation-for="Donation" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CustomUrl" class="control-label"></label>
                <text asp-for="CustomUrl" class="form-control" />
            </div>

            <div class="form-group">
                <button type="submit" class="btn btn-primary">Submit</button>
            </div>
        </form>
    </div>
    <div class="col-md-4">
        <div class="form-group">
            <label title="Profile Image" class="control-label">Profile Image</label>
            <div id="imagePreview">
                <img id="profileImage" src="@Model.ImageUrl" />
                <img id="output" hidden />
            </div>
            <div class="btn btn-danger" id="deleteImage">Remove Image</div>
        </div>

        <div class="form-group">
            <label>Image Upload</label>
            <input type="file" accept="image/*" onchange="loadFile(event)">
            <div id="imageUpload"></div>
            <div class="btn btn-light" onclick="uploadImage()">Upload</div>
        </div>
        <div class="form-group" id="tagContainer" name="tagContainer">
            <label>Tags/Genres</label>
            <input class="form-control" id="tags" placeholder="Enter three genres that describe your music" /><button class="btn btn-light" onclick="addTag()">+</button>            
            <div id="tagList" name="tagList"></div>
        </div>
        <div class="form-group" id="livestreamContainer" name="livestreamContainer">
            <div id="livestreamInput">
                <input class="form-control" id="streamLink" placeholder="Link to your livestream" /><input class="form-control" id="streamDate" type="datetime-local" value="@DateTime.Now.ToString("yyyy-MM-ddTHH:mm")" step="300" /><input class="form-control" id="streamEndDate" type="datetime-local" step="300" value="@DateTime.Now.AddHours(1).ToString("yyyy-MM-ddTHH:mm")" /><textarea class="form-control" id="streamDesc" placeholder="Decribe your stream" maxlength="300"></textarea>
                <button class="btn btn-light" onclick="addLivestream()">+</button>
            </div>
            
        </div>
    </div>
    <div class="col-md-4">
        <label>Live streams</label>
        <div id="livestreamList" name="livestreamList">

        </div>
    </div>

    <div>
        <a asp-action="Index">Back to List</a>
    </div>

    @section Scripts {
        @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
        <script src="~/js/croppie.js"></script>
        <script src="~/js/dropzone.min.js"></script>

        <script>
        getTags();
        getStreams();

        var uploadCrop = $('#imageUpload').croppie({
            viewport: {
                width: 200,
                height: 200,
                type: 'square'
            },
            boundary: {
                width: 300,
                height: 300
            }
        });

        var loadFile = function (event) {
            var output = document.getElementById('output');
            output.src = URL.createObjectURL(event.target.files[0]);
            output.onload = function () {
                 uploadCrop.croppie('bind', {
                     url: output.src
                });
                URL.revokeObjectURL(output.src) // free memory
            }
        };

        function uploadImage() {
            uploadCrop.croppie('result','blob').then(function(blob) {
                var formData = new FormData();
                formData.append('filename', 'profile.png');
                formData.append('blob', blob);
                var MyAppUrlSettings = {
                    MyUsefulUrl: '@Url.Action("UploadImage","Image")'
                }

                var request = new XMLHttpRequest();
                request.open('POST', MyAppUrlSettings.MyUsefulUrl);
                request.send(formData);
            });
        }

        //Need to do this better




        function getTags() {
            $.ajax({
                type: "GET",
                url: "../../Link/GetTags",
                success: function (data) {
                    $('#tagList').html(data);
                }
            });
        }

        function getStreams() {
            $.ajax({
                type: "GET",
                url: "../../Link/GetStreams",
                success: function (data) {
                    $('#livestreamList').html(data);
                }
            });
        }

        var tagCounter = 0
        function addTag() {
            if ($('#tagList').children('input').length < 3) {
                var tagObj = new Object();
                tagObj.Name = $('#tags').val();
                $.ajax({
                    type: "POST",
                    url: "../../Link/AddTag",
                    contentType: 'application/json',
                    data: JSON.stringify(tagObj),
                    success: function (data) {
                        var dataStr = "'" + data + "'";
                        $('#tagList').append('<input id="' + data + '" value="' + $('#tags').val() + '" onclick="tagRemove(' + dataStr + ')"/>'); $('#tags').val('');
                    }
                });
            } else {
                $('#tags').val('');
                $('#tags').attr('placeholder', 'Please remove a tag to add a new one');
            }
        }

        function addLivestream() {
            var streamObj = new Object();
            streamObj.Name = $('#streamDesc').val();
            streamObj.Description = $('#streamLink').val();
            streamObj.StartTime = $('#streamDate').val();
            streamObj.EndTime = $('#streamEndDate').val();
            $.ajax({
                type: "POST",
                url: "../../Link/AddStream",
                contentType: 'application/json',
                data: JSON.stringify(streamObj),
                success: function (data) {
                    var dataStr = "'" + data + "'";
                    $('#livestreamList').append('<div id="' + data + '" onclick="streamRemove(' + dataStr + ')"><span>-</span>' + $('#streamDesc').val() + ' on ' + $('#streamDate').val() + ' viewable at ' + $('#streamLink').val() + '</div>');
                    $('#livestreamInput').find('input').val('@DateTime.Now.ToString("yyyy-MM-ddTHH:mm")');
                }
            });
        }

        function tagRemove(id) {
            $.ajax({
                type: "POST",
                url: "../../Link/RemoveTag/" + id,
                contentType: 'application/json',
                success: function (data) {
                    $('#' + id).remove();
                    $('#tags').attr('placeholder', 'Enter three genres that describe your music');

                }
            });
        }

        function streamRemove(id) {
            $.ajax({
                type: "POST",
                url: "../../Link/RemoveStream/" + id,
                contentType: 'application/json',
                success: function (data) {
                    $('#' + id).remove();
                }
            });
        }

        $('#deleteImage').click(function () {
            $.ajax({
                type: "DELETE",
                url: "../../Image/RemoveImage?type=ProfileImage",
                success: function (data) {
                    $('#profileImage').removeAttr('src');
                }
            });
        });


        </script>
    }

CentralCoastMusic/Views/Artist/Help.cshtml
@{
    ViewData["Title"] = "Help";
}

<h1>Help</h1>

<p>If you are a consumer of this site, there's nothing I can help you with</p>